import type { ProjectFileDocument, AttendanceReportFile, ScheduleReportFile } from "../task-details/types";
import { buildTaskTracker, buildResources, buildCommunications, buildTests } from "@/lib/mockData";
import type { Task, TaskType } from "@/lib/types";

function makeSnapshot(taskType: TaskType, checkedCount: number, taskId: string, crewIdx: number): Partial<Task> {
  return {
    id: taskId,
    taskTracker: buildTaskTracker(taskType, checkedCount),
    resources: buildResources(taskId, crewIdx),
    communications: buildCommunications(taskId),
    tests: buildTests(taskId, checkedCount === 0 ? "prep" : checkedCount >= 10 ? "completion" : "pouring"),
  };
}

export const mockTaskFiles: ProjectFileDocument[] = [
  // ── WP-205: Pile Cap Foundation Works (4 versions) ──
  {
    id: "tf-205-v1", document_category: "task", task_id: "T-024", wp: "WP-205",
    task_title: "Pile Cap Foundation Works", task_type: "concrete", location: "Level 02", grid: "B5",
    created_by_pm: "James Okoye", created_at: "2026-04-12T08:30:00Z",
    task_status: "on_schedule", task_queue: "todo",
    version_type: "created", version_number: 1, progress: 0,
    scheduled_start_date: "2026-04-14", scheduled_end_date: "2026-04-20",
    description: "Cast in-situ pile caps for foundation grid B5. Includes formwork, rebar placement, and concrete pour.",
    crews: [{ id: "crew-1", name: "Steel Crew A", trade: "Structural Steel", size: 5 }],
    risk: "Medium",
    task_snapshot: makeSnapshot("concrete", 0, "T-024", 0),
  },
  {
    id: "tf-205-v2", document_category: "task", task_id: "T-024", wp: "WP-205",
    task_title: "Pile Cap Foundation Works", task_type: "concrete", location: "Level 02", grid: "B5",
    created_by_pm: "James Okoye", created_at: "2026-04-15T10:00:00Z",
    task_status: "on_schedule", task_queue: "in_progress",
    version_type: "updated", version_number: 2, progress: 35,
    scheduled_start_date: "2026-04-14", scheduled_end_date: "2026-04-20",
    description: "Formwork complete. Rebar cage assembled. Awaiting concrete delivery.",
    crews: [{ id: "crew-1", name: "Steel Crew A", trade: "Structural Steel", size: 5 }, { id: "crew-4", name: "Concrete Crew", trade: "Concrete/Finishing", size: 3 }],
    risk: "Medium",
    task_snapshot: makeSnapshot("concrete", 5, "T-024", 0),
  },
  {
    id: "tf-205-v3", document_category: "task", task_id: "T-024", wp: "WP-205",
    task_title: "Pile Cap Foundation Works", task_type: "concrete", location: "Level 02", grid: "B5",
    created_by_pm: "James Okoye", created_at: "2026-04-18T10:00:00Z",
    task_status: "behind_schedule", task_queue: "in_progress",
    version_type: "rescheduled", version_number: 3, progress: 45,
    is_rescheduled: true, reschedule_date: "2026-04-18T10:00:00Z",
    original_start_date: "2026-04-14", original_end_date: "2026-04-20",
    new_start_date: "2026-04-18", new_end_date: "2026-04-25",
    reschedule_reason: "Delayed material delivery — rebar shipment held at port",
    rescheduled_by: "James Okoye", reschedule_approved_by_pm: true,
    scheduled_start_date: "2026-04-18", scheduled_end_date: "2026-04-25",
    description: "Concrete pour delayed due to rebar shortage. Rescheduled.",
    crews: [{ id: "crew-1", name: "Steel Crew A", trade: "Structural Steel", size: 5 }, { id: "crew-4", name: "Concrete Crew", trade: "Concrete/Finishing", size: 3 }],
    risk: "High",
    task_snapshot: {
      ...makeSnapshot("concrete", 7, "T-024", 0),
      originalStartDate: "2026-04-14",
      originalEndDate: "2026-04-20",
      isRescheduled: true,
      rescheduleReason: "Delayed material delivery — rebar shipment held at port",
      rescheduledAt: "2026-04-18T10:00:00Z",
      rescheduledBy: "James Okoye",
      rescheduleApprovedByPm: true,
      pmApproved: true,
    },
  },
  {
    id: "tf-205-v4", document_category: "task", task_id: "T-024", wp: "WP-205",
    task_title: "Pile Cap Foundation Works", task_type: "concrete", location: "Level 02", grid: "B5",
    created_by_pm: "James Okoye", created_at: "2026-04-25T16:00:00Z",
    task_status: "on_schedule", task_queue: "completed",
    version_type: "completed", version_number: 4, progress: 100,
    scheduled_start_date: "2026-04-18", scheduled_end_date: "2026-04-25",
    description: "Pile caps cast successfully. Curing in progress. All inspections passed.",
    crews: [{ id: "crew-4", name: "Concrete Crew", trade: "Concrete/Finishing", size: 3 }],
    pm_approved: true, risk: "Low",
    task_snapshot: {
      ...makeSnapshot("concrete", 13, "T-024", 3),
      pmApproved: true,
    },
  },
  // ── WP-210: Column Pour — Block C (2 versions) ──
  {
    id: "tf-210-v1", document_category: "task", task_id: "T-031", wp: "WP-210",
    task_title: "Column Pour — Block C", task_type: "concrete", location: "Level 01", grid: "C3",
    created_by_pm: "James Okoye", created_at: "2026-04-15T09:00:00Z",
    task_status: "on_schedule", task_queue: "todo",
    version_type: "created", version_number: 1, progress: 0,
    scheduled_start_date: "2026-04-15", scheduled_end_date: "2026-04-22",
    description: "Pour reinforced concrete columns for Block C.",
    crews: [{ id: "crew-4", name: "Concrete Crew", trade: "Concrete/Finishing", size: 3 }],
    risk: "Low",
    task_snapshot: makeSnapshot("concrete", 0, "T-031", 3),
  },
  {
    id: "tf-210-v2", document_category: "task", task_id: "T-031", wp: "WP-210",
    task_title: "Column Pour — Block C", task_type: "concrete", location: "Level 01", grid: "C3",
    created_by_pm: "James Okoye", created_at: "2026-04-22T14:00:00Z",
    task_status: "ahead_of_schedule", task_queue: "completed",
    version_type: "completed", version_number: 2, progress: 100,
    scheduled_start_date: "2026-04-15", scheduled_end_date: "2026-04-22",
    description: "All columns poured and finished ahead of schedule.",
    crews: [{ id: "crew-4", name: "Concrete Crew", trade: "Concrete/Finishing", size: 3 }],
    pm_approved: true, risk: "Low",
    task_snapshot: {
      ...makeSnapshot("concrete", 13, "T-031", 3),
      pmApproved: true,
    },
  },
  // ── WP-198: Rebar Cage Assembly (2 versions) ──
  {
    id: "tf-198-v1", document_category: "task", task_id: "T-019", wp: "WP-198",
    task_title: "Rebar Cage Assembly — South Yard", task_type: "steel", location: "South Yard", grid: "A1",
    created_by_pm: "James Okoye", created_at: "2026-04-10T07:45:00Z",
    task_status: "on_schedule", task_queue: "todo",
    version_type: "created", version_number: 1, progress: 0,
    scheduled_start_date: "2026-04-10", scheduled_end_date: "2026-04-14",
    description: "Assemble rebar cages for South Yard foundation.",
    crews: [{ id: "crew-1", name: "Steel Crew A", trade: "Structural Steel", size: 5 }],
    risk: "Medium",
    task_snapshot: makeSnapshot("steel", 0, "T-019", 0),
  },
  {
    id: "tf-198-v2", document_category: "task", task_id: "T-019", wp: "WP-198",
    task_title: "Rebar Cage Assembly — South Yard", task_type: "steel", location: "South Yard", grid: "A1",
    created_by_pm: "James Okoye", created_at: "2026-04-14T16:30:00Z",
    task_status: "on_schedule", task_queue: "completed",
    version_type: "completed", version_number: 2, progress: 100,
    scheduled_start_date: "2026-04-10", scheduled_end_date: "2026-04-14",
    description: "All rebar cages assembled and inspected. Ready for concrete.",
    crews: [{ id: "crew-1", name: "Steel Crew A", trade: "Structural Steel", size: 5 }],
    pm_approved: true, risk: "Low",
    task_snapshot: {
      ...makeSnapshot("steel", 10, "T-019", 0),
      pmApproved: true,
    },
  },
  // ── WP-217: MEP Duct Installation (3 versions) ──
  {
    id: "tf-217-v1", document_category: "task", task_id: "T-038", wp: "WP-217",
    task_title: "MEP Duct Installation — Level 03", task_type: "mep", location: "Level 03", grid: "D6",
    created_by_pm: "James Okoye", created_at: "2026-04-16T08:00:00Z",
    task_status: "on_schedule", task_queue: "todo",
    version_type: "created", version_number: 1, progress: 0,
    scheduled_start_date: "2026-04-16", scheduled_end_date: "2026-04-23",
    description: "Install MEP ductwork on Level 03. Coordinate with electrical team.",
    crews: [{ id: "crew-2", name: "MEP Crew", trade: "Mechanical/Electrical/Plumbing", size: 6 }],
    risk: "Medium",
    task_snapshot: makeSnapshot("mep", 0, "T-038", 1),
  },
  {
    id: "tf-217-v2", document_category: "task", task_id: "T-038", wp: "WP-217",
    task_title: "MEP Duct Installation — Level 03", task_type: "mep", location: "Level 03", grid: "D6",
    created_by_pm: "James Okoye", created_at: "2026-04-19T08:00:00Z",
    task_status: "at_risk", task_queue: "in_progress",
    version_type: "rescheduled", version_number: 2, progress: 20,
    is_rescheduled: true, reschedule_date: "2026-04-19T08:00:00Z",
    original_start_date: "2026-04-16", original_end_date: "2026-04-23",
    new_start_date: "2026-04-19", new_end_date: "2026-04-27",
    reschedule_reason: "Subcontractor unavailability due to concurrent project obligation",
    rescheduled_by: "James Okoye", reschedule_approved_by_pm: true,
    scheduled_start_date: "2026-04-19", scheduled_end_date: "2026-04-27",
    description: "Rescheduled — subcontractor delayed. Work resumed Apr 19.",
    crews: [{ id: "crew-2", name: "MEP Crew", trade: "Mechanical/Electrical/Plumbing", size: 6 }],
    risk: "High",
    task_snapshot: {
      ...makeSnapshot("mep", 3, "T-038", 1),
      originalStartDate: "2026-04-16",
      originalEndDate: "2026-04-23",
      isRescheduled: true,
      rescheduleReason: "Subcontractor unavailability due to concurrent project obligation",
      rescheduledBy: "James Okoye",
      rescheduleApprovedByPm: true,
    },
  },
  {
    id: "tf-217-v3", document_category: "task", task_id: "T-038", wp: "WP-217",
    task_title: "MEP Duct Installation — Level 03", task_type: "mep", location: "Level 03", grid: "D6",
    created_by_pm: "James Okoye", created_at: "2026-04-27T15:00:00Z",
    task_status: "on_schedule", task_queue: "completed",
    version_type: "completed", version_number: 3, progress: 100,
    scheduled_start_date: "2026-04-19", scheduled_end_date: "2026-04-27",
    description: "All ductwork installed and tested. Job complete.",
    crews: [{ id: "crew-2", name: "MEP Crew", trade: "Mechanical/Electrical/Plumbing", size: 6 }],
    pm_approved: true, risk: "Low",
    task_snapshot: {
      ...makeSnapshot("mep", 10, "T-038", 1),
      pmApproved: true,
    },
  },
  // ── WP-220: Electrical Conduit Routing (1 version) ──
  {
    id: "tf-220-v1", document_category: "task", task_id: "T-042", wp: "WP-220",
    task_title: "Electrical Conduit Routing — Block A", task_type: "electrical", location: "Block A", grid: "E2",
    created_by_pm: "James Okoye", created_at: "2026-04-18T14:00:00Z",
    task_status: "on_schedule", task_queue: "in_progress",
    version_type: "created", version_number: 1, progress: 10,
    scheduled_start_date: "2026-04-19", scheduled_end_date: "2026-04-26",
    description: "Route electrical conduits through Block A ceiling and wall chases.",
    crews: [{ id: "crew-6", name: "MEP Crew B", trade: "Electrical/Plumbing", size: 3 }],
    risk: "Low",
    task_snapshot: makeSnapshot("electrical", 1, "T-042", 5),
  },
];

export const mockAttendanceFiles: AttendanceReportFile[] = [
  {
    id: "af-001", document_category: "attendance", report_date: "2026-04-18",
    crew_manager_name: "Emeka Adeyemi", present_count: 24, absent_count: 3, late_count: 2,
    linked_task_wps: ["WP-205", "WP-210"], created_at: "2026-04-18T17:00:00Z",
  },
  {
    id: "af-002", document_category: "attendance", report_date: "2026-04-17",
    crew_manager_name: "Emeka Adeyemi", present_count: 27, absent_count: 1, late_count: 1,
    linked_task_wps: ["WP-198", "WP-205"], created_at: "2026-04-17T17:00:00Z",
  },
  {
    id: "af-003", document_category: "attendance", report_date: "2026-04-16",
    crew_manager_name: "Emeka Adeyemi", present_count: 25, absent_count: 4, late_count: 0,
    linked_task_wps: ["WP-198"], created_at: "2026-04-16T17:00:00Z",
  },
  {
    id: "af-004", document_category: "attendance", report_date: "2026-04-15",
    crew_manager_name: "Emeka Adeyemi", present_count: 29, absent_count: 0, late_count: 3,
    linked_task_wps: ["WP-210", "WP-217"], created_at: "2026-04-15T17:00:00Z",
  },
];

export const mockScheduleFiles: ScheduleReportFile[] = [
  {
    id: "sf-001", document_category: "schedule",
    week_label: "Week 15", week_start: "2026-04-07", week_end: "2026-04-13",
    on_schedule_count: 3, rescheduled_count: 0, delayed_count: 0,
    created_at: "2026-04-13T17:00:00Z",
  },
  {
    id: "sf-002", document_category: "schedule",
    week_label: "Week 16", week_start: "2026-04-14", week_end: "2026-04-20",
    on_schedule_count: 4, rescheduled_count: 2, delayed_count: 1,
    created_at: "2026-04-20T17:00:00Z",
  },
  {
    id: "sf-003", document_category: "schedule",
    week_label: "Week 17", week_start: "2026-04-21", week_end: "2026-04-27",
    on_schedule_count: 3, rescheduled_count: 1, delayed_count: 0,
    created_at: "2026-04-27T17:00:00Z",
  },
];
